import { $stringifySymbol } from './lib/common.js';
import { $jsonStringify, $fnToString, $ownKeys, $get } from './lib/native.js';

/**
 * JsonScript - A creative class for stringifying JavaScript values to their literal representation
 *
 * Preserves special values like `NaN`, `undefined`, `Infinity`, `Symbol`, etc.
 */
export class JsonScript {
  private readonly indent: string;
  private readonly exists = new Set<object>();

  constructor(options?: { indent?: string | number }) {
    const indent = options?.indent ?? '';
    this.indent = typeof indent === 'number' ? ' '.repeat(indent) : indent || '';
  }

  private _stringify(value: unknown, currentIndent = ''): string {
    const nextIndent = currentIndent + this.indent;

    // Handle primitives and special values
    if (value === null) {
      return 'null';
    }
    if (value === undefined) {
      return 'undefined';
    }

    switch (typeof value) {
      case 'string':
        return $jsonStringify(value);
      case 'number':
        if (Number.isNaN(value)) {
          return 'NaN';
        } else if (value === Infinity) {
          return 'Infinity';
        } else if (value === -Infinity) {
          return '-Infinity';
        }
        return String(value);
      case 'boolean':
        return String(value);
      case 'undefined':
        return 'undefined';
      case 'function':
        return $fnToString.call(value);
      case 'symbol':
        return $stringifySymbol(value);
      case 'object':
        if (this.exists.has(value)) {
          throw new TypeError('cyclic object value');
        }
        this.exists.add(value);
      default:
        break;
    }

    // Handle Date objects
    if (value instanceof Date) {
      return `new Date(${value.getTime()})`;
    }

    // Handle RegExp objects
    if (value instanceof RegExp) {
      return value.toString();
    }

    // Handle Arrays
    if (Array.isArray(value)) {
      if (value.length === 0) {
        return '[]';
      }

      const items = value.map((item) => this.stringify(item, nextIndent));

      if (!this.indent) {
        return `[${items.join(', ')}]`;
      }

      return `[\n${nextIndent}${items.join(`,\n${nextIndent}`)}\n${currentIndent}]`;
    }

    // Handle Objects
    const keys = $ownKeys(value);

    if (keys.length === 0) {
      return '{}';
    }

    const pairs = keys.map((key: string | symbol | number) => {
      const val = $get(value, key as any);
      const keyStr = typeof key === 'string' ? key : `[${$stringifySymbol(key as symbol)}]`;
      const valueStr = this.stringify(val, nextIndent);
      return `${keyStr}: ${valueStr}`;
    });

    if (!this.indent) {
      return `{${pairs.join(', ')}}`;
    }

    return `{\n${nextIndent}${pairs.join(`,\n${nextIndent}`)}\n${currentIndent}}`;
  }

  /**
   * Convert a JavaScript value to its literal string representation
   * - basically returns what they look like in a .js file
   * - keeps special values like `NaN`, `undefined`, `Infinity`, `Symbol`, etc.
   * - distinguishes global symbols and local symbols
   * - will not preserve custom properties on Function, Date, RegExp, etc.
   * @param value The value to stringify
   * @param currentIndent Current indentation level (internal use)
   * @returns String representation of the value
   */
  stringify(value: unknown, currentIndent = ''): string {
    const result = this._stringify(value, currentIndent);
    this.exists.clear();
    return result;
  }

  /**
   * Generate a complete JavaScript module string with export default
   * @param data The data to export
   * @returns `export default something`
   */
  generateExportModule(data: unknown): string {
    const dataStr = this.stringify(data);
    return `export default ${dataStr}\n`;
  }

  /**
   * Parse the code string generated by this class
   * @param code code string
   * @returns executed result of the code
   * @throws when code has syntax error or it's broken
   */
  parse(code: string): any {
    return Function(`"use strict"; ${code.replace(/[\s]+export default[\s]+/, 'return ')}`)();
  }
}
